### ISSUE TITLE
epic: design the devbin.yml file

### ISSUE THREAD

**Issue by yeuem1vannam** [yeuem1vannam/devbin#6]
- File lives at ~/.config/devbin.yml
- Path to configuration files: docker-sync.yml / docker-compose.yml
- Namespacing

**Comment by yeuem1vannam** [comment]
ex:
```yml
global:
  verbose: false
projects:
  awesome-project:
    docker-sync: ~/Workspace/awesome-project/docker-sync.yml
    docker-compose: ~/Workspace/awesome-project/docker-compose.yml
  personal-project:
    docker-sync: ~/personal-project/.docker/docker-sync.yml
    docker-compose: ~/personal-project/.docker/docker-compose.yml
```
So the command can support the `--workspace, -w` option
```bash
$ cd ~/Workspace/awesome-project/
$ devbin rails s gateway --workspace=personal-project 
```
